name: utopic_open_file
description: A plug-in that can call native APP to open files with string result in flutter,support iOS(UTI) and android(intent)
version: 1.0.0
homepage: https://github.com/utopicnarwhal/open_file

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: com.crazecoder.openfile
        pluginClass: OpenFilePlugin
      ios:
        pluginClass: OpenFilePlugin
